name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:      
    - name: Pull the Docker image
      run: sudo docker pull nuwangayantha/cicd-pipeline:latest
    - name: Delete Old Docker container
      run: sudo docker rm -f nuwangayantha/cicd-pipeline || true
    - name: Run Docker container
      run:  sudo docker run -d -p 8080:8080 --name cicd-cont nuwangayantha/cicd-pipeline:latest